### PR TITLE
Add customHostname, certificateThumbprint for internal API App service

### PR DESCRIPTION
**Pull request by jack-education**
Added customHostname, certificateThumbprint for internal API App service.

Edited section of Internal API App service name from api to intapi.

Added outputs: InternalApiAppServiceName, DatabaseName

### CODE REVIEW

**Comment by David-B-Read** [comment]
@jack-education I've just merged a branch into master that has a web api project in it, could you merge into this branch?

**Comment by MarkFCain** [comment]
I approved, but it's breaking a check. You can't proceed with this until that's addressed

**Comment by jack-education** [comment]
> I approved, but it's breaking a check. You can't proceed with this until that's addressed

Cheers, that's occurring for the master branch as well, it's not to do with the ARM template, the web.config file is missing at this path https://github.com/SkillsFundingAgency/das-roatp-service/tree/master/src/SFA.DAS.RoATPService.Application.Api

Error:
 'No web project was found in the repository. Web projects are identified by presence of either a web.config file or wwwroot folder in the directory.'

**Comment by jack-education** [comment]
> @jack-education I've just merged a branch into master that has a web api project in it, could you merge into this branch?

I see 'This branch has no conflicts with the base branch', so your recent merges should remain in master.

**Comment by David-B-Read** [comment]
@jack-education I based the API service on SFA.DAS.AssessorService.Application.Api in the das-assessor-service, which doesn't have a web.config file, it pulls the config from Azure storage. 
Should the check for a web.config be disabled in this case?

**Pull request merged**
